name: Build APK for Kivy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. التحقق من الكود
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. إعداد بيئة Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # 3. تثبيت Buildozer ومتطلبات Android
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential ccache libncurses5 libssl-dev
          sudo apt install -y zlib1g-dev
          python -m pip install --upgrade pip
          pip install buildozer cython  # تثبيت Cython أيضًا
          
      # 4. تثبيت Java (من أجل دعم بناء APK)
      - name: Install Java
        run: |
          sudo apt-get install -y openjdk-8-jdk

      # 5. بناء APK باستخدام Buildozer
      - name: Build APK
        run: |
          buildozer android debug

      # 6. حفظ الـ APK كـ artefact باستخدام الإصدار الجديد
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
